#!/bin/env bash

# HINT: You can test the result of this script using the following command:
#echo "revalinda putri" | ./formatter

# Step 1: Read the full name and split it into two variables at once.
#   Use: read -r first_name last_name
#read -r ${revalinda,,} ${revalinda^}, ${hadinata^^}

# Step 4: Print the result in the format: "LASTNAME, Firstname"
#echo "$last_upper, $first_title"

# TODO: Replace this line with your implementation
echo "HADINATA, Revalinda"


